FROM golang:1.20-alpine

# Set the working directory to /app
WORKDIR /test

# Copy the current directory contents into the container at /app
COPY .. /test

# Run the tests
CMD ["go", "test", ".", "-bench", ".", "-benchmem", "--benchtime=2s"]